language: go

go:
  - 1.20.x

addons:
  apt:
    update: true
    packages:
      - ruby

jobs:
  include:
    - name: "Coverage"
      os: linux
      dist: jammy
      install:
        - sudo gem install coveralls-lcov
        - go install github.com/jandelgado/gcov2lcov@latest
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
        - go get ./...
      script:
        - go build -ldflags="-X main.Commit=$(git rev-parse HEAD)" cmd/koinos-transaction-store/main.go
        - go test -v github.com/koinos/koinos-transaction-store/internal/trxstore -coverprofile=coverage.out -coverpkg=./internal/trxstore
        - gcov2lcov -infile=coverage.out -outfile=coverage.info
        - golangci-lint run ./...
      after_success:
        - coveralls-lcov --repo-token "$COVERALLS_REPO_TOKEN" --service-name travis-pro coverage.info

    - name: "Docker and Integration Tests"
      os: linux
      dist: jammy
      services:
        - docker
      env:
        - TAG=`if [ $TRAVIS_BRANCH == "master" ]; then echo -n latest; else echo -n $TRAVIS_BRANCH; fi`
        - TRANSACTION_STORE=$TAG
      install:
        - git clone https://github.com/koinos/koinos-integration-tests.git
        - pushd koinos-integration-tests
        - go get ./...
        - popd
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build . -t $TRAVIS_REPO_SLUG:$TAG
      script:
        - pushd koinos-integration-tests
        - ./run.sh
      after_success:
        - |
          if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
            docker push $TRAVIS_REPO_SLUG:$TAG
          fi

notifications:
  slack:
    secure: ZmQqRCPQiJe1f3qE50uvfnAxbyn1x9Nm/u7gshjNfjDFCMeTQsFztzhDHu4fOqYgdwtkusCxBBfSrmIKABd9hi56emVuLXuqn+EOqcWuN5s29oSanMLjfgLm+yYIVvx0IS9GN4lazGh1gXZJRd1XcQXV+OtGSc+4OpjEyb1mrpg++kNrG91hURwAqj0Z+30iYs1tk+vezvlxep/tEujdsHteZwwRWKzsBFPXktSqoUpgfHf8iFW9lAuJQmbmoI/+i2vG+YFZ3nxUnWVBf6zSxPUMUkjiaXAvSYOmP7zRSYoWasKPCz0X0d/rtYRbglIFdBst7yJUIZjVjepN6cNzWAtTMMAqGmOc3ZlzgTuON1dinju1dtHaGMCaMxPxdpglF+usu7wV+a7j/ZDWRDI4kfoT2PVwuYQpKt1mwwZN0O+xDO+XYR80WCHyEEGF+Fw3dW2njcby7fD1mrTOTX4V4zr1UwtCx1v44pkOUYUpEWiQGn+JTyeHhCTK6tNs5wcYlICb6KW5h2xGCeXb1s3T9JobBxuh8TLKborH2p92FyLdc/PtO44SmwF/x1HGcb9ybqftOsHRrvCgMmULGTQX2qb1T82IafKHMdLTsZ+ZXdrxGVAm2+vzftANAXHl5JlXUDuW55R+uJUFleDry0Kv/qgPWT+C6GHd1jJ/o1pQSfY=
    on_success: never
